---
runner_org: synapticon
runner_dir: "{{ home_dir }}/actions-runner"
runner_name: ci-belgrade-linux
runner_group: Belgrade
runner_extra_labels:
  - "{{ ansible_facts.hostname }}"
  - ci-belgrade-linux
